### ISSUE TITLE
NavMeshQuery returns the same FindRandomPoint almost every time

### ISSUE THREAD

**Issue by AqlaSolutions** [Robmaister/SharpNav#11]
```
        for (int i = 0; i < 10; i++)
        {

            SVector3 startPt = new Vector3();
            int startRef = 0;
            while (!navMeshQuery.FindRandomPoint(ref startRef, ref startPt))
                Debug.WriteLine("Can't find random point");

            SVector3 endPt = new Vector3();
            int endRef = 0;

            while (!navMeshQuery.FindRandomPoint(ref endRef, ref endPt))
                Debug.WriteLine("Can't find random point");


            Debug.WriteLine("Testing finding path from " + startPt + " (" + startRef + ") to " + endPt + " (" + endRef + ")");
        }
```

Outputs:
Testing finding path from (-5,907467; 12,95738; 68,52042) (424) to (-5,907467; 12,95738; 68,52042) (424)
Testing finding path from (44,68903; 10,97468; 38,93972) (415) to (44,68903; 10,97468; 38,93972) (415)
Testing finding path from (44,68903; 10,97468; 38,93972) (415) to (44,68903; 10,97468; 38,93972) (415)
Testing finding path from (44,68903; 10,97468; 38,93972) (415) to (44,68903; 10,97468; 38,93972) (415)...

If I use different instances:

```
    for (int i = 0; i < 10; i++)
    {
            var navMeshQuery = new NavMeshQuery(_tiledNavMesh, 2048);

            SVector3 startPt = new Vector3();
            int startRef = 0;
            while (!navMeshQuery.FindRandomPoint(ref startRef, ref startPt))
                Debug.WriteLine("Can't find random point");

            navMeshQuery = new NavMeshQuery(_tiledNavMesh, 2048);

            SVector3 endPt = new Vector3();
            int endRef = 0;

            while (!navMeshQuery.FindRandomPoint(ref endRef, ref endPt))
                Debug.WriteLine("Can't find random point");


            Debug.WriteLine("Testing finding path from " + startPt + " (" + startRef + ") to " + endPt + " (" + endRef + ")");
        }
```

Testing finding path from (59,62428; 10,5812; 48,15485) (411) to (59,62428; 10,5812; 48,15485) (411)
Testing finding path from (59,62428; 10,5812; 48,15485) (411) to (59,62428; 10,5812; 48,15485) (411)
Testing finding path from (59,62428; 10,5812; 48,15485) (411) to (59,62428; 10,5812; 48,15485) (411)
Testing finding path from (59,62428; 10,5812; 48,15485) (411) to (59,62428; 10,5812; 48,15485) (411)
Testing finding path from (4,317558; 10,78998; 4,080609) (294) to (4,317558; 10,78998; 4,080609) (294)
Testing finding path from (4,317558; 10,78998; 4,080609) (294) to (4,317558; 10,78998; 4,080609) (294)
Testing finding path from (4,317558; 10,78998; 4,080609) (294) to (4,317558; 10,78998; 4,080609) (294)
...

You shouldn't create new Random object in every call because it uses Environment.TickCount seed.

**Comment by Robmaister** [comment]
@AqlaSolutions now that I'm revisiting this and cleaning up the pathfinding code, I ended up removing the `Random` parameter and taking one in the constructor mostly because it will reduce the possibility of thread-safety mistakes on the user's end.
