### ISSUE TITLE
Security bug in  unity  webplayer

### ISSUE THREAD

**Issue by sysujack** [Robmaister/SharpNav#12]
I use sharpnav in pc standalone, it's works fine. But when i deploy the app in webplayer, 
Exception  " System.MethodAccessException: Attempt to access a private/protected method failed "  was throw. 

Code  “public static readonly int SizeInBytes = Marshal.SizeOf(new Vector3())”  in Vector3.cs  lead to this problem.  it is  unmanaged code. I  comment the code line,  it work fine.

**Comment by Robmaister** [comment]
Update: removed the Unity3D target. There are already a lot of pathfinding libraries available (including the built-in one) and supporting the different casing of Unity3D's vectors will either be a pain in the ass or inefficient.

I may revisit this in the future if there's enough demand or a good reason why there should be another pathfinding solution for Unity.

**Comment by SetoKaiba** [comment]
There should be one because the built-in is without the support of runtime navmesh generation..

**Comment by Robmaister** [comment]
The Standalone version will work with Unity, you'll just have to convert SharpNav.Geometry.Vector3 into UnityEngine.Vector3.

**Comment by cr4yz** [comment]
Is it possible to build SharpNav targeting .NET 3.5 for use in Unity?

**Comment by Robmaister** [comment]
I don't thing there's anything in particular preventing that from working. If I'm using some newer API that prevents it from compiling against .NET 3.5, let me know (in a separate issue) and I'll make it work.
