### ISSUE TITLE
Path Offset / Buffer

### ISSUE THREAD

**Issue by keslabs** [Robmaister/SharpNav#24]
If I wanted to offset the path from obstacles / edges, what would be the easiest way to accomplish it? 

Any help with this would be greatly appreciated. Also, it might be helpful to put up a developers forum to encourage end-users to help each other via samples and other potentially helpful resources.

Thanks.

**Comment by Robmaister** [comment]
There's a Google Group up here now: https://groups.google.com/forum/#!forum/sharpnav

Assuming your original question was answered, I'm going to close this.
