### ISSUE TITLE
Link to examples 404

### ISSUE THREAD

**Issue by boriscallens** [Robmaister/SharpNav#40]
The readme.md contains a link https://github.com/Robmaister/SharpNav/tree/master/Examples
This page does not exists (404). I'm guessing it should be https://github.com/Robmaister/SharpNav/tree/master/Source/SharpNav.Examples

**Comment by Robmaister** [comment]
Oh yeah that was the really old structure of SharpNav.... I'll go through all the links and make sure they're not broken

**Comment by Robmaister** [comment]
All fixed, thanks for letting me know! Also realized that some of the content in the README was a bit outdated, so that's all up to date now.

**Comment by boriscallens** [comment]
awesome :+1:
