### ISSUE TITLE
Is there a way to find a random point reachable from specified?

### ISSUE THREAD

**Issue by AqlaSolutions** [Robmaister/SharpNav#44]
Now I'm trying random points in a cycle until I find any for which I can calculate a path but could you have any better solution? This is required for patrol AI where NPC choose a random point on map and walk there. I also need a variation of this to walk to a random point within range.

**Comment by Robmaister** [comment]
`FindRandomPointAroundCircle` will provide a random path that is reachable from the original point. A version that does so with any random point on the map may be a bit expensive but still useful. Will implement it, may miss the `v1.0.0` release.

**Comment by AqlaSolutions** [comment]
FindRandomPointAroundCircle finds any random point on navmesh which is inside a specified range, doesn't it? I didn't know that it ensures reachability.

**Comment by Robmaister** [comment]
Using `FindRandomPointAroundCircle` with a radius larger than your map will be marginally faster.

I can probably throw that other version together pretty quickly as a copy of `FindRandomPointAroundCircle` without the radius check

**Comment by Robmaister** [comment]
Will be present in `1.0.0-alpha.3`
