### ISSUE TITLE
Correct Behaviour in PathCorridor.MoveOverOffMeshConnection?

### ISSUE THREAD

**Issue by PixelRetro** [Robmaister/SharpNav#54]
I picked up the SharpNav only some time ago and I have little insight in what's going on, but I think I found a bug that prevented my agent from travelling over an OffMeshConnection.

The first while loop in  PathCorridor.MoveOverOffMeshConnection sets the local variables `PolyId prevRef` and `PolyId polyRef`.
Before the first iteration the variables have the following values:
prevRef = PolyId.Null
polyRef = path[0]

After first iteration:
prevRef = path[0]
polyRef = path[0]

After second iteration:
prevRef = path[0]
polyRef = path[1]

The problem is, that the npos variable needs to be incremented before setting the new value to polyRef, so prevRef and polyRef do not have the same value after the first iteration.

```c#
PolyId prevRef = PolyId.Null, polyRef = path[0];
int npos = 0;
while (npos < pathCount && polyRef != offMeshConRef)
{
	prevRef = polyRef;
	npos++;
	polyRef = path[npos];
}
```

EDIT: PullRequest: #56

**Comment by Robmaister** [comment]
Thanks for finding these issues and submitting pull requests for them, feel free to continue to do so in the future.

Testing in SharpNav is pretty lacking as it is, but I have yet to test any of the off-mesh connection functionality.

If you're using NuGet I can also wrap up a few of my own changes and push out 1.0.0-alpha.3 to make things easier for you.
