### ISSUE TITLE
Is this library appropriate for my usage?

### ISSUE THREAD

**Issue by flycast** [Robmaister/SharpNav#77]
I have a grid of X,Y points that starts as an exact grid. The grid gets distorted because the points move around somewhat. The distortion in not enough that the eye would still see it as a distorted grid. The final grid is converted to a set of x,y point cloud in no particular order. I need to identify the now distorted grid of points in such a way that I can correlate between starting location and final location and make calculations about "drift" of the point in that area of the grid. I need to do this for thousands of points.

For point at r45c22:

> Starting point location:
> 3.456, 5.52
> 

> Ending point location:
> 3.486, 5.02
> 

I am trying to measure distortion in that grid. It seems like I need to build a delauney triangulation and then be able to navigate to a certain point in that triangulation to compare starting to finished location.

Is this the right library for meshing and navigation?

Also, when I try the example from usage on the main page:
`            //prepare the geometry from your mesh data
            var tris = TriangleEnumerable.FromIndexedVertices(;

            //use the default generation settings
            var settings = NavMeshGenerationSettings.Default;
            settings.AgentHeight = 1.7f;
            settings.AgentWidth = 0.6f;

            //generate the mesh
            var navMesh = NavMesh.Generate(tris, settings);
`

I get the following error:

> 'TriangleEnumerable' does not contain a definition for 'FromIndexedVertices'

Lastly, is there some documentation that I can view that gives me the basics of all the navigation concepts? I am aware of the docs [here](http://sharpnav.com/docs/html/index.htm). But I think I need a more basic introduction to mesh navigation so I can understand the concepts in the methods, properties, etc.

**Comment by Robmaister** [comment]
Hey! I haven't really had a ton of time in the last few years to dedicate to keeping this project updated - it's probably still a pretty good base even if you'd have to make some modifications for your particular use-case.

Most of this stuff is geared towards stuffing in level's geometry and getting a navmesh out, the stuff in the middle is generally not yet set up to be used externally (i.e. generating a Delaunay hull is a [private function in PolyMeshDetail](https://github.com/Robmaister/SharpNav/blob/master/Source/SharpNav/PolyMeshDetail.cs#L1024), could be it's own class)

This project is essentially just a straight port of Recast Navigation with a few things structured more like a normal C# project. Any documentation or tutorials that use Recast are applicable for SharpNav as well.

I wrote some helper functions for putting tris in the correct format to input into navmesh generation, which is the TriangleEnumerable thing you're seeing. You most likely just have to add `using SharpNav.Geometry;` at the top of your file to fix that error.

**Comment by flycast** [comment]
Thanks so much for the quick reply.

**Comment by Robmaister** [comment]
If you don't have any more questions, I'll go ahead and close this issue in a bit
